
import {Nunito} from "next/font/google"
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import ClientOnly from "@/components/ClientOnly";
import RegisterModel from "@/components/modal/RegisterModel";
import ToasterProvider from "@/providers/ToasterProvider";
import LoginModel from "@/components/modal/LoginModel";
import getCurrentUser from "@/actions/getCurrentUser";
import RentModel from "@/components/modal/RentModel";
import SearchModal from "@/components/modal/SearchModal";

const font=Nunito({
  subsets:["latin"],

})


export const metadata = {
  title: "Airbnb",
  description: "Generated by Sai",
};

export default async function RootLayout({ children }) {
  const currentUser=await getCurrentUser()
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider/>
          <SearchModal/>
          <RentModel/>
        <RegisterModel/>
        <LoginModel/>
        <Navbar currentUser={currentUser}/>
        
        </ClientOnly>
        <div className="pb-20 pt-28">
          {children}
        </div>
        
      </body>
    </html>
  );
}
